### ISSUE TITLE
Apps cannot recognize the fingerprint api is available

### ISSUE THREAD

**Issue by li-yifei** [SemonCat/Fingerface#2]
Env:
Pixel 4 xl with November patch
Magisk 20.1
EdXposed 0.4.6.0_beta(4471) // tried YAHFA and Sandhook
(EdXposed  canary build 4476 also failed)
Build: latest version on play store

It's that something related to the November update?

**Comment by li-yifei** [comment]
closed for it's a magisk/edxposed issue

**Comment by jayeshjayan** [comment]
@li-yifei Did you fix it ? I have the same issue.

Pixel 4 XL January Patch
Magisk 20.3
EdXposed 0.4.6.0_beata(4471) (YAHFA)
